language: python
python:
  - "3.11"

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install black==23.12.1 flake8 coverage coveralls

# Run tests and code quality checks
script:
  # Check code formatting with black
  - black --check .
  # Run flake8 linting
  - flake8 .
  # Run tests with coverage
  # - coverage run --source='.' manage.py test
  - coverage run manage.py test
  - coverage report

after_success:
  - coveralls

# Deploy to AWS Elastic Beanstalk on success
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: mysite
#   env: mysite-env
#   bucket_name: elasticbeanstalk-us-east-1-123456789012
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
